### ISSUE TITLE
Update events tickets CSS

### ISSUE THREAD

**Issue by Photosynthesis** [Foundation-For-Intentional-Community/Wordpress-Theme#23]
Change fonts and colors on the Tribe Events ticketing interface (and possibly other places).

```css
/* Change button color */
.tribe-common-c-btn{
  background-color: #579C87 !important;
}

/* Get rid of Tribe fonts */
.tribe-common .tribe-common-h7, .tribe-common .tribe-common-h8, .tribe-common .tribe-common-h4, .tribe-common .tribe-common-b3, .tribe-common .tribe-common-b2, .tribe-common .tribe-tickets__buy{
	font-family: inherit !important;
}
```
